name: Create Small Artifact Manually
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create a small artifact
        run: echo "This is a small artifact file" > artifact.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: small-artifact
          path: artifact.txt
  fail_job:
     runs-on: ubuntu-latest
     steps:
      - name: Simulating a failure
        run: |
          echo "This job is supposed to fail"
          exit 1  # Forces the job to fail
